routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return redirect('home');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/notifications', 'HomeController@notifications');
    Route::group(['middleware' => 'can:occurrences', 'prefix' => 'occurrences', 'as' => 'occurrences.'], function () {
        Route::get('/', 'OccurrenceController@index')->name('index')->middleware('can:occurrences_list');
        Route::get('/create', 'OccurrenceController@create')->name('create')->middleware('can:occurrences_add');
        Route::post('/', 'OccurrenceController@store')->name('store')->middleware('can:occurrences_add');
        Route::get('/{occurrence}/edit', 'OccurrenceController@edit')->name('edit')->middleware('can:occurrences_edit');
        Route::put('/{occurrence}', 'OccurrenceController@update')->name('update')->middleware('can:occurrences_edit');
        Route::delete('/{occurrence}', 'OccurrenceController@destroy')->name('destroy')->middleware('can:occurrences_destroy');
        Route::get('/print/{occurrence}', 'ReportController@printOccurrence')->name('print')->middleware('can:occurrences_print');

    });
    Route::group(['middleware' => 'can:situations', 'prefix' => 'situations', 'as' => 'situations.'], function () {
        Route::get('/', 'SituationController@index')->name('index')->middleware('can:situations_list');
        Route::get('/create', 'SituationController@create')->name('create')->middleware('can:situations_add');
        Route::post('/', 'SituationController@store')->name('store')->middleware('can:situations_add');
        Route::get('/{situation}/edit', 'SituationController@edit')->name('edit')->middleware('can:situations_edit');
        Route::put('/{situation}', 'SituationController@update')->name('update')->middleware('can:situations_edit');
        Route::delete('/{situation}', 'SituationController@destroy')->name('destroy')->middleware('can:situations_destroy');
    });

    Route::group(['middleware' => 'can:occurrences'], function () {
        Route::group(['prefix' => 'occurrences/{occurrence}', 'as' => 'occurrences.'], function () {
            Route::get('/', function () {
                return redirect()->route('occurrences.index');
            });
            Route::post('/close', 'OccurrenceController@closeOccurrence')->name('close')->middleware('can:occurrences_close');
            Route::get('/details', 'OccurrenceController@show')->name('show');
            Route::post('/situation', 'OccurrenceController@updateSituation')->name('update.situation');
            Route::post('/message', 'MessageController@store')->name('message.store');
            Route::delete('/message/{message}', 'MessageController@destroy')->name('message.destroy');
            Route::post('/attachment', 'AttachmentController@store')->name('attachment.store');
            Route::delete('/attachment/{attachment}', 'AttachmentController@destroy')->name('attachment.destroy');
            Route::get('/attachment/{attachment}', 'AttachmentController@download')->name('attachment.download');

        });
    });

    Route::group(['middleware' => 'can:reports'], function () {
        Route::get('/reports', 'ReportController@index')->name('reports.index');
        Route::get('/results', 'ReportController@printVariousOccurrence')->name('reports.print.results');
    });

    Route::group(['middleware' => 'can:users', 'prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/', 'UserController@index')->name('index')->middleware('can:users_list');
        Route::get('/create', 'UserController@create')->name('create')->middleware('can:users_add');
        Route::post('/', 'UserController@store')->name('store')->middleware('can:users_add');
        Route::get('/{user}/edit', 'UserController@edit')->name('edit')->middleware('can:users_edit');
        Route::put('/{user}', 'UserController@update')->name('update')->middleware('can:users_edit');
        Route::delete('/{user}', 'UserController@destroy')->name('destroy')->middleware('can:users_destroy');
    });

    Route::group(['middleware' => 'can:roles', 'prefix' => 'roles', 'as' => 'roles.'], function () {
        Route::get('/', 'RoleController@index')->name('index')->middleware('can:roles_list');
        Route::get('/create', 'RoleController@create')->name('create')->middleware('can:roles_add');
        Route::post('/', 'RoleController@store')->name('store')->middleware('can:roles_add');
        Route::get('/{role}/edit', 'RoleController@edit')->name('edit')->middleware('can:roles_edit');
        Route::put('/{role}', 'RoleController@update')->name('update')->middleware('can:roles_edit');
        Route::delete('/{role}', 'RoleController@destroy')->name('destroy')->middleware('can:roles_destroy');
    });

    Route::get('/profile', 'ProfileController@edit')->name('profile.edit');
    Route::put('/profile', 'ProfileController@update')->name('profile.update');
    Route::post('/profile/password', 'ProfileController@updatePassword')->name('profile.password');
});

app/Occurrence.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Occurrence extends Model
{
    protected $fillable = ['situation_id', 'from_user_id', 'name', 'message', 'phone', 'email', 'details', 'is_closed', 'closed_at'];

    protected $dates = ['created_at', 'updated_at', 'closed_at'];

    public function situation()
    {
        return $this->belongsTo(Situation::class);
    }

    public function messages()
    {
        return $this->hasMany(Message::class);
    }

    public function attachments()
    {
        return $this->hasMany(Attachment::class);
    }

    public function fromUser()
    {
        return $this->belongsTo(User::class)->withDefault([
            'id' => 0,
            'name' => 'Anônimo',
        ]);
    }

    public function users()
    {
        return $this->belongsToMany(User::class);
    }
}

app/Http/Controllers/OccurrenceController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\OccurrenceRequest;
use App\Notifications\OccurrenceCreated;
use App\Notifications\SituationUpdated;
use App\Occurrence;
use App\Situation;
use App\User;
use Gate;
use Illuminate\Http\Request;

class OccurrenceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $situations = Situation::where('active', true)->get();

        $occurrences = Occurrence::getModel();

        if ($request->query('situation')) {
            $occurrences = $occurrences->where('situation_id', $request->query('situation'));
        }
        if (Gate::allows('administrador')) {
            $occurrences = $occurrences->get();
        } else {
            $occurrences = $occurrences->whereHas('users', function ($q) {
                $q->where('user_id', auth()->user()->id);
            })
                ->where('is_closed', false)
                ->get();
        }
        return view('occurrences.index', compact('occurrences', 'situations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $situations = Situation::where('active', true)
            ->orderBy('description', 'asc')
            ->get();
        $users = User::all();
        return view('occurrences.create', compact('situations', 'users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\OccurrenceRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(OccurrenceRequest $request)
    {
        $data = $request->all();
        $data['from_user_id'] = auth()->user()->id;
        $data['is_closed'] = $request->has('is_closed');
        $occurrence = Occurrence::create($data);
        $users = $request->to_user_id;

        $occurrence->users()->sync($users);

        foreach ($occurrence->users as $user) {
            if ($occurrence->fromUser->id != $user->id) {
                $user->notify(new OccurrenceCreated($occurrence->fromUser, $occurrence));
            }
        }

        return redirect()->route('occurrences.index')->with('success', 'Caso cadastrado com sucesso');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Occurrence  $occurrence
     * @return \Illuminate\Http\Response
     */
    public function show(Occurrence $occurrence)
    {

        $situations = Situation::where('active', true)->get();
        if (Gate::denies('administrador')) {
            $hasUser = false;
            foreach ($occurrence->users as $user) {
                if ($user->id == auth()->user()->id) {
                    $hasUser = true;
                }
            }
            if (!$hasUser) {
                return redirect()->back()->with('warning', 'Você não tem permissão para acessar esse caso');
            }
        }

        return view('occurrences.show', compact('occurrence', 'situations'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Occurrence  $occurrence
     * @return \Illuminate\Http\Response
     */
    public function edit(Occurrence $occurrence)
    {
        $situations = Situation::where('active', true)
            ->orderBy('description', 'asc')
            ->get();
        $users = User::all();

        return view('occurrences.edit', compact('occurrence', 'situations', 'users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\OccurrenceRequest  $request
     * @param  \App\Occurrence  $occurrence
     * @return \Illuminate\Http\Response
     */
    public function update(OccurrenceRequest $request, Occurrence $occurrence)
    {
        $data = $request->all();
        $occurrence->update($data);

        $users = $request->to_user_id;

        $occurrence->users()->sync($users);
        return redirect()->route('occurrences.index')->with('success', 'Caso atualizado com sucesso');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Occurrence  $occurrence
     * @return \Illuminate\Http\Response
     */
    public function destroy(Occurrence $occurrence)
    {
        $occurrence->delete();
        return redirect()->back()->with('success', 'Caso excluído com sucesso');
    }

    public function closeOccurrence(Request $request, Occurrence $occurrence)
    {
        $occurrence->is_closed = !$occurrence->is_closed;

        if ($occurrence->is_closed) {

            $occurrence->closed_at = \Carbon\Carbon::now();
        } else {
            $occurrence->closed_at = null;
        }
        $occurrence->save();

        if ($occurrence->is_closed) {
            return redirect()->back()->with('success', 'Caso encerrado com sucesso');
        }

        return redirect()->back()->with('success', 'Caso reaberto com sucesso');
    }

    public function updateSituation(Request $request, Occurrence $occurrence)
    {
        $data = $request->all();

        $occurrence->update($data);

        if ($occurrence->situation->close_occurrence) {
            $occurrence->is_closed = true;
            $occurrence->closed_at = \Carbon\Carbon::now();
            $occurrence->save();
        }

        $occurrence->fromUser->notify(new SituationUpdated(auth()->user(), $occurrence));

        if ($request->ajax) {
            return response()->json(['success' => true, 'message' => 'Status do caso foi atualizada com sucesso']);
        }

        return redirect()->back()->with('success', 'Status do caso foi atualizada com sucesso');
    }
}

resources/views/occurrences/index.blade.php
@extends('layouts.app')
@push('css')
  <link rel="stylesheet" href="/vendors/datatables.net-bs4/css/dataTables.bootstrap4.min.css">
  <style>
    @foreach($situations->groupBy('color') as $key=>$situation)
    .badge-{{substr($key,1,6)}}{
      background-color: {{$key}}40;
      color: {{$key}};
    }
    @endforeach;

  </style>
@endpush
@section('content')
<main class="main">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
    <li class="breadcrumb-item active">Casos</li>
  </ol>
  <div class="container-fluid">
    <div class="ui-view">
      <div class="animated fadeIn">
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header">
                Casos
                <div class="card-header-actions">
                  @can('occurrences_add')
                  <a href="{{route('occurrences.create')}}" class="btn btn-primary"><i class="fa fa-plus"></i> Cadastrar</a>
                  @endcan
                </div>
              </div>
              <div class="card-body">
                <div class="table-responsive">
                  <table class="table datatable">
                    <thead>
                      <tr>
                        <td>Nome</td>
                        <td>Mensagem</td>
                        <td>Telefone</td>
                        <td>Status</td>
                        <td>Encerrado?</td>
                        <td>Associado para</td>
                        <td>Criado em</td>
                        <td>Ações</td>
                      </tr>
                    </thead>
                    <tbody>
                      @foreach($occurrences as $occurrence)
                      <tr>
                        <td>{{$occurrence->name}}</td>
                        <td>{{substr_replace($occurrence->message, '...', 20)}}</td>
                        <td>{{$occurrence->phone}}</td>
                        <td><span class="badge badge-{{substr($occurrence->situation->color,1,6)}}">{{$occurrence->situation->description}}</span></td>
                        @if($occurrence->is_closed)
                        <td><span class="badge badge-success">Sim</span></td>
                        @else
                        <td><span class="badge badge-danger">Não</span></td>
                        @endif

                        <td>{{$occurrence->users->implode('name', ', ')}}</td>
                        <td>{{$occurrence->created_at->format('d/m/Y H:i')}}</td>
                        <td>
                          <div class="btn-group btn-group-sm">
                            <form action="{{route('occurrences.close', $occurrence)}}" method="post" id="close-{{$occurrence->id}}" style="display:none">@csrf</form>
                            <form action="{{ route('occurrences.destroy', $occurrence)}}" method="post">
                              @csrf
                              @method('DELETE')
                              <a href="{{route('occurrences.show', $occurrence)}}" class="btn btn-info" data-toggle="tooltip" data-placement="top" title="" data-original-title="Detalhar"><i class="fa fa-newspaper-o"></i></a>
                              @can('occurrences_edit')
                              <a href="{{route('occurrences.edit', $occurrence)}}" class="btn btn-success" data-toggle="tooltip" data-placement="top" title data-original-title="Editar"><i class="fa fa-edit"></i></a>
                              @endcan
                              @can('occurrences_close')
                              @if(!$occurrence->is_closed)
                              <a href="#" class="btn btn-light" data-toggle="tooltip" data-placement="top" title data-original-title="Encerrar" onclick="event.preventDefault();document.getElementById('close-{{$occurrence->id}}').submit()"><i class="icon-lock"></i></a>
                              @else
                              <a href="#" class="btn btn-light" data-toggle="tooltip" data-placement="top" title data-original-title="Reabrir" onclick="event.preventDefault();document.getElementById('close-{{$occurrence->id}}').submit()"><i class="icon-lock-open"></i></a>
                              @endif
                              @endcan
                              @can('occurrences_destroy')
                              <button type="submit" class="btn btn-danger" data-toggle="tooltip" data-placement="top" title data-original-title="Excluir"><i class="fa fa-trash"></i></button>
                              @endcan
                            </form>
                          </div>
                        </td>
                      </tr>
                      @endforeach
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
@stop

@push('scripts')
  <script src="/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
  <script src="/vendors/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
  <script src="/vendors/sweetalert/js/sweetalert.min.js"></script>
  <script>
    (function(){
      $('.datatable').dataTable({
        // Internationalisation. For more info refer to http://datatables.net/manual/i18n
        "language": {
          "url": '//cdn.datatables.net/plug-ins/3cfcc339e89/i18n/Portuguese-Brasil.json'
        },

        responsive: true,

        // save datatable state(pagination, sort, etc) in cookie.
        "bStateSave": true,

        "columnDefs": [ {
            "targets": [7],
            "orderable": false,
            "searchable": false
        }],
        "lengthMenu": [
            [5, 10, 20, 50, -1],
            [5, 10, 20, 50, "Todos"]
        ],

        "pageLength": 10,

        "order": [
            [1, "asc"]
        ],
      });
       $('.datatable').on('click', 'button.btn.btn-danger', function(e){
                e.preventDefault();
                let form = $(this).parents('form');
                swal({
                    title: "Confirma a exclusão?",
                    text: "Após excluído, não será possível recuperar as informações. Deseja continuar?",
                    type: "warning",
                    buttons: ['Cancelar', 'Confirmar'],
                    dangerMode: true,
                }).then(function(isConfirm){
                    if (isConfirm) {
                        form.submit();
                    }
                });
            });
    })(jQuery)
  </script>
@endpush

resources/views/occurrences/show.blade.php
@extends('layouts.app')

@push('css')
  <link rel="stylesheet" href="/vendors/select2/css/select2.min.css">
  <link rel="stylesheet" href="/vendors/select2/css/select2.bootstrap.css">

  <style>
    .ellipsis {
      text-overflow: ellipsis;
      white-space: nowrap;
      overflow: hidden;
    }
    .ellipsis:hover{
      overflow: visible;
      white-space: normal;
    }
    @foreach($situations->groupBy('color') as $key=>$situation)
    .badge-{{substr($key,1,6)}}{
      color: {{$key}};
      background-color: {{$key}}50;
    }
    .card-accent-{{substr($key,1,6)}}{
      border-top-color: {{$key}};
      border-top-width: 2px;
    }
    @endforeach;

  </style>
@endpush

@section('content')
<main class="main">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
    <li class="breadcrumb-item"><a href="{{route('occurrences.index')}}">Casos</a></li>
    <li class="breadcrumb-item active">Detalhes</li>
  </ol>
  <div class="container-fluid">
    <div class="ui-view">
      <div class="animated fadeIn">
        <div class="row">
          <div class="col-md-12">
            <div class="card card-accent-{{substr($occurrence->situation->color,1,6)}}">
              <div class="card-header">
                Caso <strong>#{{$occurrence->id}}</strong>
                <div class="card-header-actions">
                  <form action="{{route('occurrences.close', $occurrence)}}" method="post">
                    @csrf
                    @can('occurrences_close')
                    @if(!$occurrence->is_closed)
                    <button type="submit" class="btn btn-dark" data-toggle="tooltip" data-placement="top" title data-original-title="Encerrar"><i class="icon-lock"></i></button>
                    @else
                    <button type="submit" class="btn btn-dark" data-toggle="tooltip" data-placement="top" title data-original-title="Reabrir"><i class="icon-lock-open"></i></button>
                    @endif
                    @endcan
                    @can('occurrences_print')
                    <a href="#" class="btn btn-primary" data-toggle="tooltip" data-placement="top" title="" data-original-title="Imprimir" onclick="window.open('{{ route('occurrences.print', $occurrence) }}','popUpWindow','height=500,width=700,left=500,top=100,resizable=yes,scrollbars=yes,toolbar=yes,menubar=no,location=no,directories=no, status=yes');"><i class="fa fa-print"></i></a>
                    @endcan
                    </form>
                </div>
              </div>
              <div class="card-body">
                <div class="row">
                  <div class="col-sm-3"><small>Criado em <strong>{{$occurrence->created_at->format('d/m/Y H:i')}}</strong></small></div>
                  <div class="col-sm-3"><small>Por: <strong>{{$occurrence->fromUser->name}}</strong></small></div>
                  <div class="col-sm-3">
                    <small>Associado para:
                      <strong>{{$occurrence->users->implode('name', ', ')}}</strong>
                    </small></div>
                  <div class="col-sm-3"><small>Status:</small> <span class="badge badge-{{substr($occurrence->situation->color,1,6)}}">{{$occurrence->situation->description}}</span></div>
                </div>
                <div class="row mt-3">
                  <div class="col-sm-4">
                    <div><strong>{{$occurrence->name}}</strong></div>
                    <div>{{$occurrence->phone}}</div>
                    <div>{{$occurrence->email}}</div>
                  </div>
                  <div class="col-sm-8">
                    <div>{{$occurrence->message}}</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <ul class="nav nav-tabs" role="tablist">
              <li class="nav-item"><a href="#situation" data-toggle="tab" role="tab" aria-controls="situation" class="nav-link active">Status</a></li>
              <li class="nav-item"><a href="#details" data-toggle="tab" role="tab" aria-controls="details" class="nav-link">Detalhes</a></li>
              <li class="nav-item"><a href="#attachments" data-toggle="tab" role="tab" aria-controls="attachments" class="nav-link">Anexos</a></li>
            </ul>
            <div class="tab-content">
              <div class="tab-pane active" id="situation" role="tabpanel">
                <div class="row justify-content-center">
                  <div class="col-md-10">
                    <form action="{{route('occurrences.update.situation', $occurrence)}}" method="post">
                      @csrf
                      <div class="form-group">
                        <select name="situation_id" id="situation_id" class="form-control select2">
                          @foreach($situations as $situation)
                          <option value="{{$situation->id}}" {{$situation->id==$occurrence->situation_id?'selected':''}}>{{$situation->description}}</option>
                          @endforeach
                        </select>
                      </div>
                      <div class="form-group text-right">
                        <button type="submit" class="btn btn-success"><i class="fa fa-refresh"></i> Atualizar</button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
              <div class="tab-pane" id="details" role="tabpanel">
              @foreach($occurrence->messages as $message)
                <div class="row justify-content-center">
                  <div class="col-md-10">
                    <div class="card">
                      <div class="card-body">
                        <div class="row">
                          <div class="col-md-1">
                            <div class="avatar">
                              <img src="/img/avatars/{{empty(auth()->user()->avatar)?'avatar.png':auth()->user()->avatar}}" alt="Avatar" class="img-avatar">
                            </div>
                          </div>
                          <div class="col-md-9">
                            <div class="row">
                              <div class="col-md-12">
                                <div class="text-value-sm">{{$message->user->name}}</div>
                              </div>
                              <div class="col-md-12">
                                <div class="ellipsis">{{$message->message}}</div>
                              </div>
                            </div>
                          </div>
                          <div class="col-md-2 text-right">
                            <form action="{{route('occurrences.message.destroy', [$occurrence, $message])}}" method="post">
                              @csrf
                              @method('DELETE')
                              <button type="submit" class="btn btn-danger" data-toggle="tooltip" data-placement="top" title data-original-title="Excluir"><i class="fa fa-trash"></i></button>
                            </form>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              @endforeach
                <div class="row justify-content-center">
                  <div class="col-md-10">
                    <form action="{{route('occurrences.message.store', $occurrence)}}" method="post">
                      @csrf
                      <div class="form-group">
                        <label for="message">Mensagem</label>
                        <textarea name="message" id="message" class="form-control"></textarea>
                      </div>
                      <div class="form-group text-right">
                        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Salvar</button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
              <div class="tab-pane" id="attachments" role="tabpanel">
                <div class="card-group mb-4">
                @foreach($occurrence->attachments as $attachment)
                  <div class="card">
                    <div class="card-header bg-info">
                      <i class="fa fa-file-o"></i>
                      {{$attachment->filename}}
                    </div>
                    <form action="{{route('occurrences.attachment.destroy', [$occurrence, $attachment])}}" method="post">
                      @csrf
                      @method('DELETE')
                      <div class="card-body">
                        <div class="row">
                          <div class="col-md-6">
                            <a href="{{route('occurrences.attachment.download', [$occurrence, $attachment])}}" class="btn btn-success btn-sm"><i class="fa fa-download"></i> Download</a>
                          </div>
                          <div class="col-md-6">
                            <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i> Excluir</button>
                          </div>
                        </div>
                      </div>
                    </form>
                  </div>
                @endforeach
                </div>
                <div class="row justify-content-center">
                  <div class="col-md-10">
                    <form action="{{route('occurrences.attachment.store',$occurrence)}}" method="post" enctype="multipart/form-data">
                      @csrf
                      <div class="form-group">
                        <label for="filename">Arquivo</label>
                        <input type="file" name="filename" id="filename">
                      </div>
                      <div class="form-group text-right">
                        <button class="btn btn-success"><i class="fa fa-upload"></i> Upload</button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
@stop

@push('scripts')
  <script src="/vendors/select2/js/select2.min.js"></script>
  <script src="/vendors/select2/js/i18n/pt-BR.js"></script>
  <script>
    (function(){
      $('.select2').select2({theme: 'bootstrap'});
      @if($occurrence->is_closed)
      $('form input[type="text"]').prop('disabled', true);
      $('form textarea').prop('disabled', true);
      $('form select').prop('disabled', true);
      $('form input[type="file"]').prop('disabled', true);
      $('form button.btn.btn-success').prop('disabled', true);
      $('form button.btn.btn-danger').prop('disabled', true);
      @endif
    })(jQuery)
  </script>

@endpush