routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return redirect('home');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/notifications', 'HomeController@notifications');
    Route::group(['middleware' => 'can:occurrences', 'prefix' => 'occurrences', 'as' => 'occurrences.'], function () {
        Route::get('/', 'OccurrenceController@index')->name('index')->middleware('can:occurrences_list');
        Route::get('/create', 'OccurrenceController@create')->name('create')->middleware('can:occurrences_add');
        Route::post('/', 'OccurrenceController@store')->name('store')->middleware('can:occurrences_add');
        Route::get('/{occurrence}/edit', 'OccurrenceController@edit')->name('edit')->middleware('can:occurrences_edit');
        Route::put('/{occurrence}', 'OccurrenceController@update')->name('update')->middleware('can:occurrences_edit');
        Route::delete('/{occurrence}', 'OccurrenceController@destroy')->name('destroy')->middleware('can:occurrences_destroy');
        Route::get('/print/{occurrence}', 'ReportController@printOccurrence')->name('print')->middleware('can:occurrences_print');

    });
    Route::group(['middleware' => 'can:situations', 'prefix' => 'situations', 'as' => 'situations.'], function () {
        Route::get('/', 'SituationController@index')->name('index')->middleware('can:situations_list');
        Route::get('/create', 'SituationController@create')->name('create')->middleware('can:situations_add');
        Route::post('/', 'SituationController@store')->name('store')->middleware('can:situations_add');
        Route::get('/{situation}/edit', 'SituationController@edit')->name('edit')->middleware('can:situations_edit');
        Route::put('/{situation}', 'SituationController@update')->name('update')->middleware('can:situations_edit');
        Route::delete('/{situation}', 'SituationController@destroy')->name('destroy')->middleware('can:situations_destroy');
    });

    Route::group(['middleware' => 'can:occurrences'], function () {
        Route::group(['prefix' => 'occurrences/{occurrence}', 'as' => 'occurrences.'], function () {
            Route::get('/', function () {
                return redirect()->route('occurrences.index');
            });
            Route::post('/close', 'OccurrenceController@closeOccurrence')->name('close')->middleware('can:occurrences_close');
            Route::get('/details', 'OccurrenceController@show')->name('show');
            Route::post('/situation', 'OccurrenceController@updateSituation')->name('update.situation');
            Route::post('/message', 'MessageController@store')->name('message.store');
            Route::delete('/message/{message}', 'MessageController@destroy')->name('message.destroy');
            Route::post('/attachment', 'AttachmentController@store')->name('attachment.store');
            Route::delete('/attachment/{attachment}', 'AttachmentController@destroy')->name('attachment.destroy');
            Route::get('/attachment/{attachment}', 'AttachmentController@download')->name('attachment.download');

        });
    });

    Route::group(['middleware' => 'can:reports'], function () {
        Route::get('/reports', 'ReportController@index')->name('reports.index');
        Route::get('/results', 'ReportController@printVariousOccurrence')->name('reports.print.results');
    });

    Route::group(['middleware' => 'can:users', 'prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/', 'UserController@index')->name('index')->middleware('can:users_list');
        Route::get('/create', 'UserController@create')->name('create')->middleware('can:users_add');
        Route::post('/', 'UserController@store')->name('store')->middleware('can:users_add');
        Route::get('/{user}/edit', 'UserController@edit')->name('edit')->middleware('can:users_edit');
        Route::put('/{user}', 'UserController@update')->name('update')->middleware('can:users_edit');
        Route::delete('/{user}', 'UserController@destroy')->name('destroy')->middleware('can:users_destroy');
    });

    Route::group(['middleware' => 'can:roles', 'prefix' => 'roles', 'as' => 'roles.'], function () {
        Route::get('/', 'RoleController@index')->name('index')->middleware('can:roles_list');
        Route::get('/create', 'RoleController@create')->name('create')->middleware('can:roles_add');
        Route::post('/', 'RoleController@store')->name('store')->middleware('can:roles_add');
        Route::get('/{role}/edit', 'RoleController@edit')->name('edit')->middleware('can:roles_edit');
        Route::put('/{role}', 'RoleController@update')->name('update')->middleware('can:roles_edit');
        Route::delete('/{role}', 'RoleController@destroy')->name('destroy')->middleware('can:roles_destroy');
    });

    Route::get('/profile', 'ProfileController@edit')->name('profile.edit');
    Route::put('/profile', 'ProfileController@update')->name('profile.update');
    Route::post('/profile/password', 'ProfileController@updatePassword')->name('profile.password');
});

resources/views/layouts/partials/aside.blade.php
<aside class="aside-menu">
  <ul class="nav nav-tabs" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" href="#timeline" role="tab">
        <i class="icon-list"></i>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#messages" role="tab">
        <i class="icon-speech"></i>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#settings" role="tab">
        <i class="icon-settings"></i>
      </a>
    </li>
  </ul>
  <!-- Tab panes-->
  <div class="tab-content">
    <div class="tab-pane active" id="timeline" role="tabpanel">
      <div class="list-group list-group-accent">
        <div class="list-group-item list-group-item-accent-secondary bg-light text-center font-weight-bold text-muted text-uppercase small">Today</div>
        <div class="list-group-item list-group-item-accent-warning list-group-item-divider">
          <div class="avatar float-right">
            <img class="img-avatar" src="/img/avatars/7.jpg" alt="admin@bootstrapmaster.com">
          </div>
          <div>Meeting with
            <strong>Lucas</strong>
          </div>
          <small class="text-muted mr-3">
            <i class="icon-calendar"></i>  1 - 3pm</small>
          <small class="text-muted">
            <i class="icon-location-pin"></i>  Palo Alto, CA</small>
        </div>
        <div class="list-group-item list-group-item-accent-info">
          <div class="avatar float-right">
            <img class="img-avatar" src="/img/avatars/4.jpg" alt="admin@bootstrapmaster.com">
          </div>
          <div>Skype with
            <strong>Megan</strong>
          </div>
          <small class="text-muted mr-3">
            <i class="icon-calendar"></i>  4 - 5pm</small>
          <small class="text-muted">
            <i class="icon-social-skype"></i>  On-line</small>
        </div>
        <div class="list-group-item list-group-item-accent-secondary bg-light text-center font-weight-bold text-muted text-uppercase small">Tomorrow</div>
        <div class="list-group-item list-group-item-accent-danger list-group-item-divider">
          <div>New UI Project -
            <strong>deadline</strong>
          </div>
          <small class="text-muted mr-3">
            <i class="icon-calendar"></i>  10 - 11pm</small>
          <small class="text-muted">
            <i class="icon-home"></i>  creativeLabs HQ</small>
          <div class="avatars-stack mt-2">
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="/img/avatars/2.jpg" alt="admin@bootstrapmaster.com">
            </div>
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="/img/avatars/3.jpg" alt="admin@bootstrapmaster.com">
            </div>
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="/img/avatars/4.jpg" alt="admin@bootstrapmaster.com">
            </div>
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="/img/avatars/5.jpg" alt="admin@bootstrapmaster.com">
            </div>
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="/img/avatars/6.jpg" alt="admin@bootstrapmaster.com">
            </div>
          </div>
        </div>
        <div class="list-group-item list-group-item-accent-success list-group-item-divider">
          <div>
            <strong>#10 Startups.Garden</strong> Meetup</div>
          <small class="text-muted mr-3">
            <i class="icon-calendar"></i>  1 - 3pm</small>
          <small class="text-muted">
            <i class="icon-location-pin"></i>  Palo Alto, CA</small>
        </div>
        <div class="list-group-item list-group-item-accent-primary list-group-item-divider">
          <div>
            <strong>Team meeting</strong>
          </div>
          <small class="text-muted mr-3">
            <i class="icon-calendar"></i>  4 - 6pm</small>
          <small class="text-muted">
            <i class="icon-home"></i>  creativeLabs HQ</small>
          <div class="avatars-stack mt-2">
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="/img/avatars/2.jpg" alt="admin@bootstrapmaster.com">
            </div>
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="/img/avatars/3.jpg" alt="admin@bootstrapmaster.com">
            </div>
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="/img/avatars/4.jpg" alt="admin@bootstrapmaster.com">
            </div>
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="/img/avatars/5.jpg" alt="admin@bootstrapmaster.com">
            </div>
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="/img/avatars/6.jpg" alt="admin@bootstrapmaster.com">
            </div>
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="/img/avatars/7.jpg" alt="admin@bootstrapmaster.com">
            </div>
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="/img/avatars/8.jpg" alt="admin@bootstrapmaster.com">
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="tab-pane p-3" id="messages" role="tabpanel">
      <div class="message">
        <div class="py-3 pb-5 mr-3 float-left">
          <div class="avatar">
            <img class="img-avatar" src="/img/avatars/7.jpg" alt="admin@bootstrapmaster.com">
            <span class="avatar-status badge-success"></span>
          </div>
        </div>
        <div>
          <small class="text-muted">Lukasz Holeczek</small>
          <small class="text-muted float-right mt-1">1:52 PM</small>
        </div>
        <div class="text-truncate font-weight-bold">Lorem ipsum dolor sit amet</div>
        <small class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</small>
      </div>
      <hr>
      <div class="message">
        <div class="py-3 pb-5 mr-3 float-left">
          <div class="avatar">
            <img class="img-avatar" src="/img/avatars/7.jpg" alt="admin@bootstrapmaster.com">
            <span class="avatar-status badge-success"></span>
          </div>
        </div>
        <div>
          <small class="text-muted">Lukasz Holeczek</small>
          <small class="text-muted float-right mt-1">1:52 PM</small>
        </div>
        <div class="text-truncate font-weight-bold">Lorem ipsum dolor sit amet</div>
        <small class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</small>
      </div>
      <hr>
      <div class="message">
        <div class="py-3 pb-5 mr-3 float-left">
          <div class="avatar">
            <img class="img-avatar" src="/img/avatars/7.jpg" alt="admin@bootstrapmaster.com">
            <span class="avatar-status badge-success"></span>
          </div>
        </div>
        <div>
          <small class="text-muted">Lukasz Holeczek</small>
          <small class="text-muted float-right mt-1">1:52 PM</small>
        </div>
        <div class="text-truncate font-weight-bold">Lorem ipsum dolor sit amet</div>
        <small class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</small>
      </div>
      <hr>
      <div class="message">
        <div class="py-3 pb-5 mr-3 float-left">
          <div class="avatar">
            <img class="img-avatar" src="/img/avatars/7.jpg" alt="admin@bootstrapmaster.com">
            <span class="avatar-status badge-success"></span>
          </div>
        </div>
        <div>
          <small class="text-muted">Lukasz Holeczek</small>
          <small class="text-muted float-right mt-1">1:52 PM</small>
        </div>
        <div class="text-truncate font-weight-bold">Lorem ipsum dolor sit amet</div>
        <small class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</small>
      </div>
      <hr>
      <div class="message">
        <div class="py-3 pb-5 mr-3 float-left">
          <div class="avatar">
            <img class="img-avatar" src="/img/avatars/7.jpg" alt="admin@bootstrapmaster.com">
            <span class="avatar-status badge-success"></span>
          </div>
        </div>
        <div>
          <small class="text-muted">Lukasz Holeczek</small>
          <small class="text-muted float-right mt-1">1:52 PM</small>
        </div>
        <div class="text-truncate font-weight-bold">Lorem ipsum dolor sit amet</div>
        <small class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</small>
      </div>
    </div>
    <div class="tab-pane p-3" id="settings" role="tabpanel">
      <h6>Settings</h6>
      <div class="aside-options">
        <div class="clearfix mt-4">
          <small>
            <b>Option 1</b>
          </small>
          <label class="switch switch-label switch-pill switch-success switch-sm float-right">
            <input class="switch-input" type="checkbox" checked="">
            <span class="switch-slider" data-checked="On" data-unchecked="Off"></span>
          </label>
        </div>
        <div>
          <small class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</small>
        </div>
      </div>
      <div class="aside-options">
        <div class="clearfix mt-3">
          <small>
            <b>Option 2</b>
          </small>
          <label class="switch switch-label switch-pill switch-success switch-sm float-right">
            <input class="switch-input" type="checkbox">
            <span class="switch-slider" data-checked="On" data-unchecked="Off"></span>
          </label>
        </div>
        <div>
          <small class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</small>
        </div>
      </div>
      <div class="aside-options">
        <div class="clearfix mt-3">
          <small>
            <b>Option 3</b>
          </small>
          <label class="switch switch-label switch-pill switch-success switch-sm float-right">
            <input class="switch-input" type="checkbox">
            <span class="switch-slider" data-checked="On" data-unchecked="Off"></span>
          </label>
        </div>
      </div>
      <div class="aside-options">
        <div class="clearfix mt-3">
          <small>
            <b>Option 4</b>
          </small>
          <label class="switch switch-label switch-pill switch-success switch-sm float-right">
            <input class="switch-input" type="checkbox" checked="">
            <span class="switch-slider" data-checked="On" data-unchecked="Off"></span>
          </label>
        </div>
      </div>
      <hr>
      <h6>System Utilization</h6>
      <div class="text-uppercase mb-1 mt-4">
        <small>
          <b>CPU Usage</b>
        </small>
      </div>
      <div class="progress progress-xs">
        <div class="progress-bar bg-info" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
      </div>
      <small class="text-muted">348 Processes. 1/4 Cores.</small>
      <div class="text-uppercase mb-1 mt-2">
        <small>
          <b>Memory Usage</b>
        </small>
      </div>
      <div class="progress progress-xs">
        <div class="progress-bar bg-warning" role="progressbar" style="width: 70%" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100"></div>
      </div>
      <small class="text-muted">11444GB/16384MB</small>
      <div class="text-uppercase mb-1 mt-2">
        <small>
          <b>SSD 1 Usage</b>
        </small>
      </div>
      <div class="progress progress-xs">
        <div class="progress-bar bg-danger" role="progressbar" style="width: 95%" aria-valuenow="95" aria-valuemin="0" aria-valuemax="100"></div>
      </div>
      <small class="text-muted">243GB/256GB</small>
      <div class="text-uppercase mb-1 mt-2">
        <small>
          <b>SSD 2 Usage</b>
        </small>
      </div>
      <div class="progress progress-xs">
        <div class="progress-bar bg-success" role="progressbar" style="width: 10%" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"></div>
      </div>
      <small class="text-muted">25GB/256GB</small>
    </div>
  </div>
</aside>

resources/views/layouts/partials/footer.blade.php
<footer class="app-footer">
  <div class="ml-auto">

    <span>&copy; {{date('Y')}} <a href="https://fenixinvestigacoes.com.br">Fenix Investigações</a></span>
  </div>
</footer>

resources/views/layouts/partials/header.blade.php
<header class="app-header navbar">
  <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" type="button" data-toggle="sidebar-show">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="{{route('home')}}">
    <img class="navbar-brand-full" src="/img/logo.png" height="40" alt="Fenix Investigações">
    <img class="navbar-brand-minimized" src="/img/logo_mini.png" height="40" alt="Fenix Investigações">
  </a>
  <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button" data-toggle="sidebar-lg-show">
    <span class="navbar-toggler-icon"></span>
  </button>
  <ul class="nav navbar-nav ml-auto">
    <audio id="sound-notification">
      <source src="/sounds/appointed.mp3" type="audio/mpeg">
      <source src="/sounds/appointed.ogg" type="audio/ogg">
    </audio>

    <li class="nav-item dropdown d-md-down-none">
      <a class="nav-link" id="notifications" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <i class="icon-bell"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right dropdown-menu-xl" id="notificationsMenu">
        <div class="dropdown-header text-center">
          <strong>Sem notificações</strong>
        </div>
      </div>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <img class="img-avatar" src="/img/avatars/{{empty(auth()->user()->avatar)?'avatar.png':auth()->user()->avatar}}" alt="admin@bootstrapmaster.com">
      </a>
      <div class="dropdown-menu dropdown-menu-right">
        <div class="dropdown-header text-center">
          <strong>Configurações</strong>
        </div>
        <a class="dropdown-item" href="{{route('profile.edit')}}">
          <i class="fa fa-user"></i> Perfil</a>
        <form action="{{route('logout')}}" method="post" id="logout" style="display:none">
          @csrf
        </form>
        <a class="dropdown-item" href="#" onclick="event.preventDefault();document.getElementById('logout').submit()">
          <i class="fa fa-lock"></i> Sair</a>
      </div>
    </li>
  </ul>
</header>

resources/views/layouts/partials/sidebar.blade.php
<div class="sidebar">
  <nav class="sidebar-nav">
    <ul class="nav">
      <li class="nav-item">
        <a class="nav-link" href="{{route('home')}}">
          <i class="nav-icon cui-dashboard"></i> Dashboard
        </a>
      </li>
      @can('occurrences')
      <li class="nav-item nav-dropdown {{request()->is('occurrences*')?'open':''}}">
        <a class="nav-link nav-dropdown-toggle" href="#">
          <i class="nav-icon icon-layers"></i> Casos</a>
        <ul class="nav-dropdown-items">
          @can('occurrences_add')
          <li class="nav-item">
            <a href="{{route('occurrences.create')}}" class="nav-link">
              <i class="nav-icon fa fa-plus"></i> Cadastrar</a>
          </li>
          @endcan
          @can('occurrences_list')
          <li class="nav-item">
            <a href="{{route('occurrences.index')}}" class="nav-link">
              <i class="nav-icon icon-magnifier"></i> Pesquisar</a>
          </li>
          @endcan
        </ul>
      </li>
      @endcan
      @can('situations')
      <li class="nav-item nav-dropdown {{request()->is('situations*')?'open':''}}">
        <a class="nav-link nav-dropdown-toggle" href="#">
          <i class="nav-icon icon-directions"></i> Status</a>
        <ul class="nav-dropdown-items">
          @can('situations_add')
          <li class="nav-item">
            <a href="{{route('situations.create')}}" class="nav-link">
              <i class="nav-icon fa fa-plus"></i> Cadastrar</a>
          </li>
          @endcan
          @can('situations_list')
          <li class="nav-item">
            <a href="{{route('situations.index')}}" class="nav-link">
              <i class="nav-icon icon-magnifier"></i> Pesquisar</a>
          </li>
          @endcan
        </ul>
      </li>
      @endcan
      @can('reports')
      <li class="nav-item nav-dropdown {{request()->is('reports*')?'open':''}}">
        <a class="nav-link" href="{{route('reports.index')}}">
          <i class="nav-icon icon-printer"></i> Relatório</a>
      </li>
      @endcan
      @can('users')
      <li class="nav-title">Configurações</li>
      @endcan
      @can('users')
      <li class="nav-item nav-dropdown">
        <a class="nav-link nav-dropdown-toggle" href="#">
          <i class="nav-icon icon-people"></i> Usuários</a>
        <ul class="nav-dropdown-items">
          @can('users_add')
          <li class="nav-item">
            <a href="{{route('users.create')}}" class="nav-link">
              <i class="nav-icon fa fa-plus"></i> Cadastrar</a>
          </li>
          @endcan
          @can('users_list')
          <li class="nav-item">
            <a href="{{route('users.index')}}" class="nav-link">
              <i class="nav-icon icon-magnifier"></i> Pesquisar</a>
          </li>
          @endcan
        </ul>
      </li>
      @endcan
      @can('roles')
      <li class="nav-item nav-dropdown">
        <a class="nav-link nav-dropdown-toggle" href="#">
          <i class="nav-icon cui-lock-locked"></i> Perfis</a>
        <ul class="nav-dropdown-items">
          @can('roles_add')
          <li class="nav-item">
            <a href="{{route('roles.create')}}" class="nav-link">
              <i class="nav-icon fa fa-plus"></i> Cadastrar</a>
          </li>
          @endcan
          @can('roles_list')
          <li class="nav-item">
            <a href="{{route('roles.index')}}" class="nav-link">
              <i class="nav-icon icon-magnifier"></i> Pesquisar</a>
          </li>
          @endcan
        </ul>
      </li>
      @endcan
    </ul>
  </nav>
  <button class="sidebar-minimizer brand-minimizer" type="button"></button>
</div>

resources/views/layouts/partials/toastr.blade.php
@if (session('success'))

  <script>
      toastr.options.closeButton = true;
      toastr.success("{{session('success')}}", 'Sucesso')
  </script>
@endif

@if (session('error'))

  <script>
      toastr.options.closeButton = true;
      toastr.error("{{session('error')}}", 'Erro')
  </script>
@endif

@if (session('info'))

  <script>
      toastr.options.closeButton = true;
      toastr.info("{{session('info')}}", 'Informação')
  </script>
@endif

@if (session('warning'))

  <script>
      toastr.options.closeButton = true;
      toastr.warning("{{session('warning')}}", 'Atenção')
  </script>
@endif

@if ($errors->any())
  <script>
      toastr.options.closeButton = true;
      @foreach($errors->all() as $error)
          toastr.error("{{$error}}",'Atenção')
      @endforeach

  </script>
@endif