routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return redirect('home');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/notifications', 'HomeController@notifications');
    Route::group(['middleware' => 'can:occurrences', 'prefix' => 'occurrences', 'as' => 'occurrences.'], function () {
        Route::get('/', 'OccurrenceController@index')->name('index')->middleware('can:occurrences_list');
        Route::get('/create', 'OccurrenceController@create')->name('create')->middleware('can:occurrences_add');
        Route::post('/', 'OccurrenceController@store')->name('store')->middleware('can:occurrences_add');
        Route::get('/{occurrence}/edit', 'OccurrenceController@edit')->name('edit')->middleware('can:occurrences_edit');
        Route::put('/{occurrence}', 'OccurrenceController@update')->name('update')->middleware('can:occurrences_edit');
        Route::delete('/{occurrence}', 'OccurrenceController@destroy')->name('destroy')->middleware('can:occurrences_destroy');
        Route::get('/print/{occurrence}', 'ReportController@printOccurrence')->name('print')->middleware('can:occurrences_print');

    });
    Route::group(['middleware' => 'can:situations', 'prefix' => 'situations', 'as' => 'situations.'], function () {
        Route::get('/', 'SituationController@index')->name('index')->middleware('can:situations_list');
        Route::get('/create', 'SituationController@create')->name('create')->middleware('can:situations_add');
        Route::post('/', 'SituationController@store')->name('store')->middleware('can:situations_add');
        Route::get('/{situation}/edit', 'SituationController@edit')->name('edit')->middleware('can:situations_edit');
        Route::put('/{situation}', 'SituationController@update')->name('update')->middleware('can:situations_edit');
        Route::delete('/{situation}', 'SituationController@destroy')->name('destroy')->middleware('can:situations_destroy');
    });

    Route::group(['middleware' => 'can:occurrences'], function () {
        Route::group(['prefix' => 'occurrences/{occurrence}', 'as' => 'occurrences.'], function () {
            Route::get('/', function () {
                return redirect()->route('occurrences.index');
            });
            Route::post('/close', 'OccurrenceController@closeOccurrence')->name('close')->middleware('can:occurrences_close');
            Route::get('/details', 'OccurrenceController@show')->name('show');
            Route::post('/situation', 'OccurrenceController@updateSituation')->name('update.situation');
            Route::post('/message', 'MessageController@store')->name('message.store');
            Route::delete('/message/{message}', 'MessageController@destroy')->name('message.destroy');
            Route::post('/attachment', 'AttachmentController@store')->name('attachment.store');
            Route::delete('/attachment/{attachment}', 'AttachmentController@destroy')->name('attachment.destroy');
            Route::get('/attachment/{attachment}', 'AttachmentController@download')->name('attachment.download');

        });
    });

    Route::group(['middleware' => 'can:reports'], function () {
        Route::get('/reports', 'ReportController@index')->name('reports.index');
        Route::get('/results', 'ReportController@printVariousOccurrence')->name('reports.print.results');
    });

    Route::group(['middleware' => 'can:users', 'prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/', 'UserController@index')->name('index')->middleware('can:users_list');
        Route::get('/create', 'UserController@create')->name('create')->middleware('can:users_add');
        Route::post('/', 'UserController@store')->name('store')->middleware('can:users_add');
        Route::get('/{user}/edit', 'UserController@edit')->name('edit')->middleware('can:users_edit');
        Route::put('/{user}', 'UserController@update')->name('update')->middleware('can:users_edit');
        Route::delete('/{user}', 'UserController@destroy')->name('destroy')->middleware('can:users_destroy');
    });

    Route::group(['middleware' => 'can:roles', 'prefix' => 'roles', 'as' => 'roles.'], function () {
        Route::get('/', 'RoleController@index')->name('index')->middleware('can:roles_list');
        Route::get('/create', 'RoleController@create')->name('create')->middleware('can:roles_add');
        Route::post('/', 'RoleController@store')->name('store')->middleware('can:roles_add');
        Route::get('/{role}/edit', 'RoleController@edit')->name('edit')->middleware('can:roles_edit');
        Route::put('/{role}', 'RoleController@update')->name('update')->middleware('can:roles_edit');
        Route::delete('/{role}', 'RoleController@destroy')->name('destroy')->middleware('can:roles_destroy');
    });

    Route::get('/profile', 'ProfileController@edit')->name('profile.edit');
    Route::put('/profile', 'ProfileController@update')->name('profile.update');
    Route::post('/profile/password', 'ProfileController@updatePassword')->name('profile.password');
});

app/Situation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Situation extends Model
{
    protected $fillable = ['description', 'color', 'active', 'close_occurrence'];

    protected $dates = ['created_at', 'updated_at'];

    protected $cast = ['active' => 'boolean'];

    public function messages()
    {
        return $this->hasMany(Message::class);
    }

    public function occurrences()
    {
        return $this->hasMany(Occurrence::class);
    }
}

app/Http/Controllers/SituationController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SituationRequest as Request;
use App\Situation;
use Illuminate\Database\QueryException;

class SituationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $situations = Situation::all();

        return view('situations.index', compact('situations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('situations.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\SituationRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $data['active'] = $request->has('active');
        $data['close_occurrence'] = $request->has('close_occurrence');
        $situation = Situation::create($data);
        return redirect()->route('situations.index')->with('success', 'Status criado com sucesso');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Situation  $situation
     * @return \Illuminate\Http\Response
     */
    public function show(Situation $situation)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Situation  $situation
     * @return \Illuminate\Http\Response
     */
    public function edit(Situation $situation)
    {
        return view('situations.edit', compact('situation'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\SituationRequest  $request
     * @param  \App\Situation  $situation
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Situation $situation)
    {
        $data = $request->all();
        $data['active'] = $request->has('active');
        $data['close_occurrence'] = $request->has('close_occurrence');
        $situation->update($data);
        return redirect()->route('situations.index')->with('success', 'Status atualizado com sucesso');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Situation  $situation
     * @return \Illuminate\Http\Response
     */
    public function destroy(Situation $situation)
    {
        try {
            $situation->delete();
        } catch (QueryException $e) {

            return redirect()->back()->with('error', 'Não foi possível excluir o status pois ele está associado a um ou mais registros');
        }

        return redirect()->back()->with('success', 'Status excluído com sucesso');
    }
}

resources/views/situations/create.blade.php
@extends('layouts.app')

@push('css')
  <link rel="stylesheet" href="/vendors/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css">
@endpush

@section('content')
<main class="main">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
    <li class="breadcrumb-item"><a href="{{route('situations.index')}}">Status</a></li>
    <li class="breadcrumb-item active">Cadastrar</li>
  </ol>
  <div class="container-fluid">
    <div class="ui-view">
      <div class="animated fadeIn">
        <div class="row">
          <div class="col-md-8 offset-md-2">
            <div class="card">
              <form action="{{route('situations.store')}}" method="post">
              @csrf
                <div class="card-header">
                  <strong>Status</strong>
                  <small>Cadastro</small>
                </div>
                <div class="card-body">
                  <div class="form-group">
                    <label for="description">Descrição</label>
                    <input type="text" name="description" id="description" class="form-control @error('description') is-invalid @enderror" value="{{old('description')}}">
                    @error('description')
                      <span class="invalid-feedback" role="alert">
                        <strong>{{$message}}</strong>
                      </span>
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="color">Cor</label>
                    <input type="text" name="color" id="color" class="form-control @error('color') is-invalid @enderror" value="{{old('color')}}">
                    @error('color')
                      <span class="invalid-feedback" role="alert">
                        <strong>{{$message}}</strong>
                      </span>
                    @enderror
                  </div>
                  <div class="form-group">
                    <div class="row">
                      <div class="col-md-2">
                        <label for="">Encerra Caso?</label>
                      </div>
                      <div class="col-md-10">
                        <label class="switch switch-label switch-outline-success-alt">
                          <input type="checkbox" name="close_occurrence" id="close_occurrence" class="switch-input" value="1" {{old('close_occurrence')?'checked':''}}>
                          <span class="switch-slider" data-checked="✓" data-unchecked="✕"></span>
                        </label>
                      </div>
                    </div>
                    @error('close_occurrence')
                      <span class="invalid-feedback" role="alert">
                        <strong>{{$message}}</strong>
                      </span>
                    @enderror
                  </div>
                  <div class="form-group">
                    <div class="row">
                      <div class="col-md-1">
                        <label for="">Ativo?</label>
                      </div>
                      <div class="col-md-11">
                        <label class="switch switch-label switch-outline-success-alt">
                          <input type="checkbox" name="active" id="active" class="switch-input" value="1" {{old('active')?'checked':''}}>
                          <span class="switch-slider" data-checked="✓" data-unchecked="✕"></span>
                        </label>
                      </div>
                    </div>
                    @error('active')
                      <span class="invalid-feedback" role="alert">
                        <strong>{{$message}}</strong>
                      </span>
                    @enderror
                  </div>
                </div>
                <div class="card-footer text-right">
                  <button class="btn btn-success" type="submit">
                    <i class="icon cui-check"></i> Salvar
                  </button>
                  <a href="{{route('situations.index')}}" class="btn btn-secondary"><i class="fa fa-close"></i> Cancelar</a>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
@stop

@push('scripts')
  <script src="/vendors/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js"></script>
  <script>
    $(function () {
      $('#color').colorpicker();
    });
  </script>
@endpush

resources/views/situations/edit.blade.php
@extends('layouts.app')

@push('css')
  <link rel="stylesheet" href="/vendors/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css">
@endpush

@section('content')
<main class="main">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
    <li class="breadcrumb-item"><a href="{{route('situations.index')}}">Status</a></li>
    <li class="breadcrumb-item active">Editar</li>
  </ol>
  <div class="container-fluid">
    <div class="ui-view">
      <div class="animated fadeIn">
        <div class="row">
          <div class="col-md-8 offset-md-2">
            <div class="card">
              <form action="{{route('situations.update', $situation)}}" method="post">
              @csrf
              @method('PUT')
                <div class="card-header">
                  <strong>Status</strong>
                  <small>Edição</small>
                </div>
                <div class="card-body">
                  <div class="form-group">
                    <label for="description">Descrição</label>
                    <input type="text" name="description" id="description" class="form-control @error('description') is-invalid @enderror" value="{{old('description', $situation->description)}}">
                    @error('description')
                      <span class="invalid-feedback" role="alert">
                        <strong>{{$message}}</strong>
                      </span>
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="color">Cor</label>
                    <input type="text" name="color" id="color" class="form-control @error('color') is-invalid @enderror" value="{{old('color', $situation->color)}}">
                    @error('color')
                      <span class="invalid-feedback" role="alert">
                        <strong>{{$message}}</strong>
                      </span>
                    @enderror
                  </div>
                  <div class="form-group">
                    <div class="row">
                      <div class="col-md-2">
                        <label for="">Encerra Caso?</label>
                      </div>
                      <div class="col-md-10">
                        <label class="switch switch-label switch-outline-success-alt">
                          <input type="checkbox" name="close_occurrence" id="close_occurrence" class="switch-input" value="1" {{old('close_occurrence', $situation->close_occurrence)?'checked':''}}>
                          <span class="switch-slider" data-checked="✓" data-unchecked="✕"></span>
                        </label>
                      </div>
                    </div>
                    @error('close_occurrence')
                      <span class="invalid-feedback" role="alert">
                        <strong>{{$message}}</strong>
                      </span>
                    @enderror
                  </div>
                  <div class="form-group">
                    <div class="row">
                      <div class="col-md-1">
                        <label for="">Ativo?</label>
                      </div>
                      <div class="col-md-11">
                        <label class="switch switch-label switch-outline-success-alt">
                          <input type="checkbox" name="active" id="active" class="switch-input" value="1" {{old('active', $situation->active)?'checked':''}}>
                          <span class="switch-slider" data-checked="✓" data-unchecked="✕"></span>
                        </label>
                      </div>
                    </div>
                    @error('active')
                      <span class="invalid-feedback" role="alert">
                        <strong>{{$message}}</strong>
                      </span>
                    @enderror
                  </div>
                </div>
                <div class="card-footer text-right">
                  <button class="btn btn-success" type="submit">
                    <i class="icon cui-check"></i> Salvar
                  </button>
                  <a href="{{route('situations.index')}}" class="btn btn-secondary"><i class="fa fa-close"></i> Cancelar</a>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
@stop

@push('scripts')
  <script src="/vendors/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js"></script>
  <script>
    $(function () {
      $('#color').colorpicker();
    });
  </script>
@endpush

resources/views/situations/index.blade.php
@extends('layouts.app')
@push('css')
  <link rel="stylesheet" href="/vendors/datatables.net-bs4/css/dataTables.bootstrap4.min.css">
  <style>
    @foreach($situations->groupBy('color') as $key=>$situation)
    .badge-{{substr($key,1,6)}}{
      background-color: {{$key}}40;
      color: {{$key}};
    }
    @endforeach;

  </style>
@endpush
@section('content')
<main class="main">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
    <li class="breadcrumb-item active">Status</li>
  </ol>
  <div class="container-fluid">
    <div class="ui-view">
      <div class="animated fadeIn">
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header">
                Status
                <div class="card-header-actions">
                  @can('situations_add')
                  <a href="{{route('situations.create')}}" class="btn btn-primary"><i class="fa fa-plus"></i> Cadastrar</a>
                  @endcan
                </div>
              </div>
              <div class="card-body">
                <div class="table-responsive">
                  <table class="table datatable">
                    <thead>
                      <tr>
                        <td>Descrição</td>
                        <td>Cor</td>
                        <td>Ativo?</td>
                        <td>Encerra Caso?</td>
                        <td>Criado em</td>
                        <td>Ações</td>
                      </tr>
                    </thead>
                    <tbody>
                      @foreach($situations as $situation)
                      <tr>
                        <td>{{$situation->description}}</td>
                        <td><span class="badge badge-{{substr($situation->color,1,6)}}">{{$situation->color}}</span></td>
                        @if($situation->active)
                        <td><span class="badge badge-success">Sim</span></td>
                        @else
                        <td><span class="badge badge-danger">Não</span></td>
                        @endif
                        @if($situation->close_occurrence)
                        <td><span class="badge badge-success">Sim</span></td>
                        @else
                        <td><span class="badge badge-danger">Não</span></td>
                        @endif
                        <td>{{$situation->created_at->format('d/m/Y H:i')}}</td>
                        <td>
                          <div class="btn-group btn-group-sm">
                            <form action="{{ route('situations.destroy', $situation)}}" method="post">
                              @csrf
                              @method('DELETE')
                              @can('situations_edit')
                              <a href="{{route('situations.edit', $situation)}}" class="btn btn-success"><i class="fa fa-edit"></i></a>
                              @endcan
                              @can('situations_destroy')
                              <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i></button>
                              @endcan
                            </form>
                          </div>
                        </td>
                      </tr>
                      @endforeach
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
@stop

@push('scripts')
  <script src="/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
  <script src="/vendors/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
  <script src="/vendors/sweetalert/js/sweetalert.min.js"></script>
  <script>
    (function(){
      $('.datatable').dataTable({
        // Internationalisation. For more info refer to http://datatables.net/manual/i18n
        "language": {
          "url": '//cdn.datatables.net/plug-ins/3cfcc339e89/i18n/Portuguese-Brasil.json'
        },

        responsive: true,

        // save datatable state(pagination, sort, etc) in cookie.
        "bStateSave": true,

        "columnDefs": [ {
            "targets": [4],
            "orderable": false,
            "searchable": false
        }],
        "lengthMenu": [
            [5, 10, 20, 50, -1],
            [5, 10, 20, 50, "Todos"]
        ],

        "pageLength": 10,

        "order": [
            [1, "asc"]
        ],
      });
       $('.datatable').on('click', 'button.btn.btn-danger', function(e){
                e.preventDefault();
                let form = $(this).parents('form');
                swal({
                    title: "Confirma a exclusão?",
                    text: "Após excluído, não será possível recuperar as informações. Deseja continuar?",
                    type: "warning",
                    buttons: ['Cancelar', 'Confirmar'],
                    dangerMode: true,
                }).then(function(isConfirm){
                    if (isConfirm) {
                        form.submit();
                    }
                });
            });
    })(jQuery)
  </script>
@endpush